patterns = {
    "ALGOLIA":          r'(ALGOLIA_ADMIN_KEY+)',
    "DROPBOX":          r'(([a-zA-Z0-9]{8})+_+([a-zA-Z0-9]{24})+-+([a-zA-Z0-9]{5})+_+([a-zA-Z0-9]{23})+)',
    "AWS_1":            r'(([a-zA-Z]{4})+\.+([a-zA-Z]{3})+\.+([a-zA-Z0-9]{8})+-+([a-zA-Z0-9]{4})+-+([a-zA-Z0-9]{4})-+([a-zA-Z0-9]{4})+-+([a-zA-Z0-9]{12})+)',
    "AWS_2":            r'(AKIA+[A-Z0-9]+)',
    "AWS_3":            r'(([a-zA-Z0-9]{3})+-+([a-zA-Z0-9]{26})+)',
    "AWS_5":            r'(AWS_ACCESS_KEY_ID+)',
    "AWS_4":            r'(AWS_SECRET_ACCESS_KEY+)',
    "AWS_6":            r'(AWS_SESSION_TOKEN+)',
    "AZURE":            r'(Ocp-Apim-Subscription-Key+)',
    "CODE_CLIMATE":     r'(CODECLIMATE_+[A-Z0-9]+)',
    "CODE_CLIMATE_2":   r'([a-z0-9]{64})',
    "FACEBOOK_1":       r'((https:\/\/graph.facebook.com\/)+([0-9]{10})+_+([0-9]{17})+\/reactions+)',
    "FACEBOOK_2":       r'(https:\/\/graph.facebook.com\/+([0-9]{10})+_+([0-9]{17})+\/reactions\?type=+([a-zA-Z]{3})+&method=+([a-zA-Z])+&access_token=)',
    "FACEBOOK_3":       r'((https:\/\/graph.facebook.com\/v+([0-9]{1}))+\.+([0-9]{1})+\/+([0-9]{16})+\/comments\?format=json&access_token=+([a-zA-Z0-9])+)',
    "FILEZILLA":        r'(<Pass encoding="base64">+([a-zA-Z0-9=\/])+<\/Pass>)',
    "GITHUB":           r'(ghp_+([a-zA-Z0-9])+)',
    "GOOGLE":           r'(AIza+([a-zA-Z0-9])+)',
    "RSA_KEY":          r'(-----BEGIN RSA PRIVATE KEY-----+)',
    "HEROKU_1":         r'(heroku_[a-zA-Z0-9]+)',
    "HEROKU_2":         r'(([a-z0-9]{8})+-+([a-z0-9]{4})+-+([a-z0-9]{4})+-+([a-z0-9]{4})+-+([a-z0-9]{12})+)',
    "HTTP_BASIC_AUTH":  r'(Authorization: Basic +([a-zA-Z0-9\/=])+)',
    "CERT":             r'(-----BEGIN CERTIFICATE-----\nMII+)',
    "EC_KEY":           r'(-----BEGIN EC PRIVATE KEY-----+)',
    "PEM_KEY":          r'(-----BEGIN PRIVATE KEY-----\nMII+)',
    "PGP":              r'(-----BEGIN PGP PRIVATE KEY BLOCK-----+)',
    "NPM_1":            r'(_auth = +([a-zA-Z0-9\/=])+)',
    "NPM_2":            r'(\/\/registry.npmjs.org\/:_authToken=+([0-9a-z]{8})+-+([0-9a-z]{4})+-+([0-9a-z]{4})+-+([0-9a-z]{4})+-([0-9a-z]{12})+)',
    "OUTLOOK_WEBHOOK":  r'(https://outlook.office.com/webhook/+([0-9a-z]{8})+-+([0-9a-z]{4})+-+([0-9a-z]{4})+-+([0-9a-z]{4})+-([0-9a-z]{12})+@+)',
    "PAYPAL":           r'(access_token\$production\$+([0-9a-z]{16})+\$+([0-9a-z]{32})+)',
    "SAUCE":            r'(SAUCE_ACCESS_KEY=+([a-z0-9]{8})+-+([a-z0-9]{4})+-([a-z0-9]{4})+-([a-z0-9]{4})+-([a-z0-9]{12})+)',
    "SHOPIFY_1":        r'(shopify_app_secret+)',
    "SHOPIFY_2":        r'(shpss_+([0-9a-z]{32})+)',
    "SHOPIFY_3":        r'(shopifyAppKey+)',
    "SHOPIFY_4":        r'(shopifyAppSecret+)',
    "SLACK_HOOK":       r'(https:\/\/hooks.slack.com\/services\/+([a-zA-Z0-9]{9})+\/+([a-zA-Z0-9]{9})+\/+([a-zA-Z0-9]{24})+)',
    "SLACK_TOKEN":      r'(xoxp-+([0-9]{12})+-+([0-9]{12})+-+([0-9]{12})+-+([0-9a-zA-Z]{32})+)',
    "SONAR_QUBE":       r'(sonarqube_stg_k=+([0-9a-zA-Z]{40})+)',
    # "SSH_1":            r'(sshpass -p +(.*)+ ssh +([a-zA-Z0-9])+@+([.*])+)',
    "SSH_2":            r'(sshpass -p +)'
}